// SERVER COMPONENT — no 'use client' — generateStaticParams works here
import ProjectClient from "./ProjectClient";

const PROJECTS = {
  "bio-corner":{ name:"BIO.CO.R.N.ER", domain:"green", status:"Active", fund:"CIRCULOOS · Horizon Europe", fundUrl:"https://circuloos.eu/open-calls/", tags:["Bio-based","Circular Economy","Emilia-Romagna"], period:"2023–2026", partners:["CIRCULOOS (Horizon Europe)","Grant Agreement 101092295"], subtitle:"BIO-waste for a COordinated and Regenerative New supply chain of eco-sustainable building materials in Emilia-Romagna.", about:"The BIO.CO.R.N.ER project proposes a new circular, regional value chain that transforms bio-waste from agri-food, aquaculture, and marine residues into eco-sustainable building materials. Based in the Emilia-Romagna region, the project pioneers low-carbon, bio-based mortars and building components.", context:"Funded by CIRCULOOS Horizon Europe project — 2nd Open Call (Grant Agreement 101092295).", leveryRole:["Integration of CIRCULOOS digital tools ensuring efficient circular economy data flows.","Research and development of digital traceability tools including NGSI-LD data modelling and Digital Product Passport design.","Mapping of the information chain and identification of key actors across the bio-waste valorisation network."] },
  "w2w":{ name:"W2W", domain:"green", status:"Active", fund:"Horizon Europe", fundUrl:"", tags:["Wood Waste","Circular Economy","Bio-based","Façade Systems"], period:"2023–2027", partners:["Horizon Europe","Grant Agreement 101138789"], subtitle:"Transforming Wood Waste into Valuable Resource for a Greener Future.", about:"W2W develops a comprehensive framework for multi-dimensional cascade valorisation of wood from Construction & Demolition and furniture waste, targeting closed-loop systems where materials are continuously reused.", context:"Funded by the European Union under Horizon Europe (Grant Agreement 101138789).", leveryRole:["Validation of W2W upcycled wood products for prefabricated façade panels.","Benchmarking and comparative analysis against conventional materials.","Façade system engineering and technical documentation.","Scientific dissemination."], images:["https://lirp.cdn-website.com/f62b8008/dms3rep/multi/opt/1753693908168-1920w.jpeg"] },
  "mc20":{ name:"MC2.0", domain:"digital", status:"Active", fund:"Horizon Europe · GA 101096139", fundUrl:"", tags:["BIPV","Mass Customisation","Building Envelope","LCA"], period:"2022–2026", partners:["Horizon Europe","Grant Agreement 101096139","Glass to Power","GUALINI"], subtitle:"Mass Customization 2.0 for Integrated Photovoltaic building envelopes.", about:"MC2.0 demonstrates how automated manufacturing of Integrated Photovoltaic elements using mass customisation can deliver a cost breakthrough in IPV façades, windows and roofs.", context:"Funded by the European Union under Horizon Europe (Grant Agreement 101096139).", leveryRole:["Market needs analysis and testing protocol definition for IPV products.","Ecodesign MCDA methodology for ESPR-aligned prioritisation.","LCA and LCC analysis for building use cases.","Digital Product Passport design for BIPV products."] },
  "prometheus":{ name:"PROMETHEUS", domain:"xr", status:"Completed", fund:"Horizon Europe", fundUrl:"", tags:["XR","Augmented Reality","Building Maintenance","WebXR"], period:"2022–2024", partners:["Horizon Europe","Exvirience S.r.l."], subtitle:"Augmented and Virtual Reality for Construction — from design review to on-site maintenance.", about:"PROMETHEUS delivered a groundbreaking XR-based WebXR application for remote maintenance of adaptive building envelopes, enabling real-time interactive maintenance via PCs and tablets.", context:"Funded by the European Union. Developed with EXVIRIENCE S.r.l. Directly led to the ARyze platform commercialisation.", leveryRole:["Definition of XR use cases for building operations and maintenance.","Integration of BIM, Digital Product Passport and building management data into the XR interface.","Technology transfer from research outputs to the ARyze product."], images:["https://lirp.cdn-website.com/f62b8008/dms3rep/multi/opt/Immagine-2024-10-04-104240-1920w.jpg"] },
  "winloop":{ name:"WINLOOP", domain:"green", status:"Active", fund:"Horizon Europe", fundUrl:"", tags:["Windows","Circular Economy","End-of-Life","Digital Product Passport"], period:"2023–2027", partners:["Horizon Europe"], subtitle:"Developing technologies and business models for closing the life cycle of windows.", about:"WINLOOP addresses one of the least circular product categories in construction. The project develops technologies, digitalisation tools and business models to close the lifecycle of windows from design to end-of-life recovery.", context:"Funded under Horizon Europe. The consortium includes window manufacturers, recyclers, digital tool developers and research institutions.", leveryRole:["Digital Product Passport design for window systems.","Lifecycle assessment (LCA) of current and circular window scenarios.","Circular business model definition and end-of-life recovery pathways."] },
  "bios-mater":{ name:"BIOS MATER", domain:"green", status:"Active", fund:"Horizon Europe", fundUrl:"", tags:["Bio-based","Construction Products","Sustainability","Market Validation"], period:"2023–2027", partners:["Horizon Europe"], subtitle:"Re-designing the construction sector through sustainable bio-based construction products.", about:"BIOS MATER develops sustainable and functional bio-based construction products with competitive market performance, addressing the full innovation chain from raw material sourcing to market deployment.", context:"Funded under Horizon Europe. Targets manufacturers looking to transition toward bio-based material portfolios ahead of ESPR requirements.", leveryRole:["Product development support across material selection, formulation and prototype testing.","Lifecycle assessment (LCA) to quantify environmental performance.","Market analysis — identifying target segments, regulatory pathways and competitive positioning."] },
  "agro-builder":{ name:"Agro.build.ER", domain:"green", status:"Active", fund:"Regional · Emilia-Romagna", fundUrl:"", tags:["Agro-waste","Circular Economy","Bio-based","Regional Supply Chain"], period:"2023–2025", partners:["Regione Emilia-Romagna"], subtitle:"Developing a circular agro-waste value chain for the sustainable building sector in Emilia-Romagna.", about:"Agro.build.ER develops a circular agro-waste value chain for the sustainable building sector, creating rural-urban synergies. The project identifies agricultural residues with construction material potential and builds supply chain infrastructure within the regional innovation ecosystem.", context:"Funded by the Regione Emilia-Romagna as part of regional circular economy and green innovation programmes.", leveryRole:["Circular business model design — identifying viable pathways for agro-waste valorisation.","Material valorisation strategy — technical assessment of agro-waste streams.","Stakeholder engagement and supply chain mapping."] },
  "digi4bio":{ name:"Digi4BioMat", domain:"digital", status:"Active", fund:"Horizon Europe", fundUrl:"", tags:["Digital Product Passport","Bio-based","Circular Economy","ESPR"], period:"2023–2027", partners:["Horizon Europe"], subtitle:"Digital Product Passport infrastructure to upscale circular business models for bio-based construction materials.", about:"Digi4BioMat develops DPP infrastructure specifically for bio-based construction materials, enabling manufacturers to scale circular business models across EU supply chains aligned with ESPR.", context:"Funded under Horizon Europe. Directly informs the development of the DeePPy platform.", leveryRole:["DPP platform design — defining data models, user interfaces and API structures.","Regulatory alignment against ESPR, EPD and circular economy frameworks.","Piloting DPP implementation with bio-based material manufacturers."] },
  "pv-igu":{ name:"PV-IGU", domain:"digital", status:"Completed", fund:"Direct service · Glass to Power", fundUrl:"", tags:["BIPV","Building Envelope","Technology Transfer","Glass to Power"], period:"2022–2023", partners:["Glass to Power S.p.A."], subtitle:"Supporting Glass to Power in the technological integration of BIPV systems into building envelopes.", about:"PV-IGU was a direct R&D service engagement with Glass to Power, an Italian manufacturer of transparent organic photovoltaic modules for building integration.", context:"Delivered as a direct consulting and R&D service to Glass to Power S.p.A., running in parallel with Levery's involvement in the MC2.0 Horizon Europe project.", leveryRole:["Technical documentation — building envelope integration specifications.","Building envelope integration analysis — evaluating compatibility with façade systems.","Market strategy support — identifying target building typologies and competitive positioning."] },
  "belm":{ name:"BELM", domain:"digital", status:"Active", fund:"Horizon Europe", fundUrl:"", tags:["Digital Twin","Lifecycle Management","Sustainability","Building Systems"], period:"2023–2027", partners:["Horizon Europe"], subtitle:"Built Environment Lifecycle Management Assistance — digital tools for whole-life assessment of building systems.", about:"BELM develops digital tools for whole-life assessment and management of building systems and components, addressing the lack of integrated digital infrastructure for tracking building performance across the full lifecycle.", context:"Funded under Horizon Europe. Builds on digital twin technology, IoT integration and lifecycle assessment methodology.", leveryRole:["Platform architecture — contributing to the design of the BELM digital infrastructure.","Sustainability assessment modules — developing LCA and LCC calculation tools.","Data interoperability — ensuring compatibility with Digital Product Passport standards and ESPR."] },
};

export async function generateStaticParams() {
  return Object.keys(PROJECTS).map(slug => ({ slug }));
}

export default function ProjectPage({ params }) {
  const project = PROJECTS[params?.slug] || PROJECTS["bio-corner"];
  return <ProjectClient project={project} />;
}
